feat: add page component
konsulin-id/smart-forms pull request #1
Opened 2024-07-26 15:21 UTC by ryuuzake

Here are some proves that the page component works

| Storybook                                                                                 | Playground                                                                                |
|-------------------------------------------------------------------------------------------|-------------------------------------------------------------------------------------------|
| ![image](https://github.com/user-attachments/assets/b90c2670-f579-4f74-875b-1bdc74fe4b3f) | ![image](https://github.com/user-attachments/assets/2d62c4fc-970e-43a7-95ab-cd39ae4db889) |
| ![image](https://github.com/user-attachments/assets/43c08e8b-b444-45fc-b2bd-a840bdc754a2) | ![image](https://github.com/user-attachments/assets/578cc470-5395-4fdd-aaa9-285f6740231a) |

2024-07-26 15:29 UTC, ardihikaru commented on packages/smart-forms-renderer/src/utils/fhirpath.ts
> -  if (!questionnaireResponse.item) {
yang ini kenapa dihilangkan ya mas?

2024-07-26 15:29 UTC, ardihikaru requested changes
nitip cek dikit

2024-07-26 15:30 UTC, ardihikaru approved these changes

2024-07-26 15:34 UTC, ryuuzake commented on packages/smart-forms-renderer/src/utils/fhirpath.ts
> -  if (!questionnaireResponse.item) {
itu perubahan dari main branch aehrc/smart-forms
bisa dilihat di commit ini
https://github.com/konsulin-id/smart-forms/pull/1/commits/d3fd1a8d37bc454b53283675ab4abcb7c2685ede

2024-07-27 14:21 UTC, ryuuzake commented
Here are some proves that the page component works

| Storybook                                                                                 | Playground                                                                                |
|-------------------------------------------------------------------------------------------|-------------------------------------------------------------------------------------------|
| ![image](https://github.com/user-attachments/assets/14fdc9ed-9f42-41cb-aafa-df015f2091f4) | ![image](https://github.com/user-attachments/assets/06c71fa6-c31d-4366-8351-9c25a754126b) |
| ![image](https://github.com/user-attachments/assets/f6f6eb70-cc09-4cec-9fc6-ca0f104a0863) | ![image](https://github.com/user-attachments/assets/09f3a840-f74c-46ab-b5c8-afeefbf4d2da) |

2024-07-27 15:09 UTC, merged